name: "CI"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format check
        run: |
          nix fmt -- --no-cache
          git diff --exit-code

      - name: Build
        run: nix build

      - name: Test
        run: nix develop --command purs-nix test

      - name: Flake check
        run: nix flake check
